config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    root 'pages#index', as: :root
  end

  root 'pages#public_index', as: :public_root

  resources :clients

  resources :invoices do
    resources :activities
  end

end

app/models/invoice.rb
# == Schema Information
#
# Table name: invoices
#
#  id         :integer          not null, primary key
#  number     :integer
#  date       :date
#  client_id  :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Invoice < ActiveRecord::Base
  # Relations
  has_many :activities
  belongs_to :client
  belongs_to :user


  accepts_nested_attributes_for :activities
end

app/controllers/invoices_controller.rb
# == Schema Information
#
# Table name: invoices
#
#  id         :integer          not null, primary key
#  number     :integer
#  date       :date
#  client_id  :integer
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class InvoicesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_invoice, only: [:edit, :show, :update, :destroy]

  def index
    @invoices = Invoice.where(user_id: current_user).all
  end

  def show
  end

  def new
    @invoice = Invoice.new
    @clients = Client.all
    @activity = Activity.new
    @invoice.activities.build
  end

  def create
    @invoice = Invoice.new(invoice_params)
    @invoice.user_id = current_user.id

    if @invoice.save
      redirect_to invoices_path
      flash[:notice] = :saved
    else
      redirect_to new_invoice_path

      @invoice.errors.messages.each do |c|
        flash[:alert] = c[1].first
      end
    end
  end

  def edit
    @clients = Client.all
  end

  def update
    if @invoice.update(invoice_params)
      redirect_to invoices_path
      flash[:notice] = :saved
    else
      @invoice.errors.messages.each do |c|
        flash[:alert] = c[1].first
      end
      render :edit
    end
  end

  def destroy
    redirect_to invoices_path if @invoice.destroy
  end

  private

  def set_invoice
    @invoice = Invoice.find(params[:id])
  end

  def invoice_params
    params.require(:invoice).permit(:number, :date, :client_id, :user_id,
                                    activities_attributes: [ :id, :description,
                                                             :amount,
                                                             :price_ex_fat ])
  end
end

app/views/invoices/edit.html.erb
<h1 class="page-header">Create a new invoice</h1>
<%= form_for(@invoice) do |f| %>
  <h3>Client Information</h3>
  <div class="well">
    <div class="form-group">
      <%= f.label :client_id %><br />
      <%= f.collection_select(:client_id, @clients, :id, :select_option, {},
                                      {class: 'form-control'}) %>
    </div>

    <div class="form-group">
      <%= f.label :number, 'Invoice Number' %><br />
      <%= f.text_field :number, class: "form-control" %>
    </div>

    <%= f.label :date %><br />
    <div class="input-group date"  id="datepicker">
      <%= f.text_field :date, value: Time.now.strftime("%d-%m-%Y"), class: "form-control" %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <h3>Activities</h3>
  <div class="panel panel-default">
    <table class="table">
      <thead>
        <th>Description</th>
        <th>Amount</th>
        <th colspan="2">Price (Ex VAT)</th>
      </thead>
      <tbody>
        <%= f.fields_for :activities, @activity do |a| %>
          <tr>
            <td class="col-md-7">
              <%= a.text_field :description, class: "form-control", placeholder: 'Activity Description' %>
            </td>
            <td class="col-md-1">
            <%= a.text_field :amount, class: "form-control", placeholder: 'Amount'  %>
            </td>
            <td class="col-md-2">
              <%= a.text_field :price_ex_fat, class: "form-control", placeholder: 'Price (Ex. VAT)'  %>
            </td>
            <td class="col-md-2">
              <%= link_to (content_tag :span, (), class: 'fa fa-remove fa-fw'), '#', class: 'btn btn-danger', id: 'remove' %>
              <%= link_to (content_tag :span, (), class: 'fa fa-plus fa-fw'), '#', class: 'btn btn-success', id: 'add' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="panel-footer">

    </div>
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
    <%= link_to "Back", invoices_path, class: "btn btn-default"  %>
  </div>

  <script type="text/javascript">
    $(function () {
      $('#datepicker').datetimepicker({
        format: "DD-MM-YYYY"
      });
    });
  </script>
<% end %>

app/views/invoices/index.html.erb
<h1 class="page-header">My Invoices</h1>

<div class="panel panel-default">
  <div class="panel-heading">
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Number</th>
        <th>Client</th>
        <th>Date</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @invoices.each do |i| %>
        <tr>
          <td>
            <%= i.number %>
          </td>
          <td>
            <%= i.client.name %>
          </td>
          <td>
            <%= i.date %>
          </td>
          <td>
            <%= link_to (content_tag :span, (), class: 'fa fa-eye fa-fw'), invoice_path(i), class: 'btn btn-primary', title: 'Show'  %>
            <%= link_to (content_tag :span, (), class: 'fa fa-pencil fa-fw'), edit_invoice_path(i), class: 'btn btn-info', title: 'Edit'  %>
            <%= link_to (content_tag :span, (), class: 'fa fa-remove fa-fw'), invoice_path(i), class: 'btn btn-danger', title: 'Delete', method: :delete, data: { :confirm => "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="panel-footer">
    <%= link_to (content_tag :span, (), class: 'fa fa-plus fa-fw') + " New Invoice", new_invoice_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/invoices/new.html.erb
<h1 class="page-header">Create a new invoice</h1>
<%= form_for @invoice do |f| %>
  <div class="well">
    <div class="form-group">
      <%= f.label :client_id %><br />
      <%= f.collection_select(:client_id, @clients, :id, :select_option, {},
                                      {class: 'form-control'}) %>
    </div>

    <div class="form-group">
      <%= f.label :number, 'Invoice Number' %><br />
      <%= f.text_field :number, value: generated_invoice_number, class: "form-control" %>
    </div>

    <%= f.label :date %><br />
    <div class="input-group date"  id="datepicker">
      <%= f.text_field :date, value: Time.now.strftime("%d-%m-%Y"), class: "form-control" %>
      <span class="input-group-addon">
        <span class="glyphicon glyphicon-calendar"></span>
      </span>
    </div>
  </div>

  <h3>Activities</h3>
  <div class="panel panel-default">
    <table class="table">
      <thead>
        <th>Description</th>
        <th>Amount</th>
        <th colspan="2">Price (Ex VAT)</th>
      </thead>
      <tbody>
        <%= f.fields_for :activities, @activity do |a| %>
          <tr>
            <td class="col-md-7">
              <%= a.text_field :description, class: "form-control", placeholder: 'Activity Description' %>
            </td>
            <td class="col-md-1">
            <%= a.text_field :amount, class: "form-control", placeholder: 'Amount'  %>
            </td>
            <td class="col-md-2">
              <%= a.text_field :price_ex_fat, class: "form-control", placeholder: 'Price (Ex. VAT)'  %>
            </td>
            <td class="col-md-2">
              <%= link_to (content_tag :span, (), class: 'fa fa-remove fa-fw'), '#', class: 'btn btn-danger', id: 'remove' %>
              <%= link_to (content_tag :span, (), class: 'fa fa-plus fa-fw'), '#', class: 'btn btn-success', id: 'add' %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <div class="panel-footer">

    </div>
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
    <%= link_to "Back", invoices_path, class: "btn btn-default"  %>
  </div>

  <script type="text/javascript">
    $(function () {
      $('#datepicker').datetimepicker({
        format: "DD-MM-YYYY"
      });
    });
  </script>
<% end %>

app/views/invoices/show.html.erb
<h1 class="page-header">View Invoice</h1>
<div class="form-group">
    <%= link_to "Back", invoices_path, class: "btn btn-default"  %>
  </div>
<div class="row">
  <div class="well col-md-10 col-md-offset-1 invoice">
    <div class="row">
      <div class="col-md-9">
        <div class="logo-area">
          <%= image_tag @invoice.user.company_logo.web, class: 'logo img-responsive' %>
        </div>
        <table class="table table-condensed">
          <tbody>
            <tr>
              <td>Invoice Date:</td><td><%= @invoice.date %></td>
            </tr>
            <tr>
              <td> Invoice Number:</td><td><%= @invoice.number %></td>
            </tr>
            <tr>
              <td>Client Number:</td><td><%= "%.6d" % @invoice.client.client_number %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="col-md-3 user-address">
        <%= current_user.company_name %> <br>
        <%= current_user.name %> <br>
        <%= current_user.street %> <%= current_user.number %><br>
        <%= current_user.zipcode %> <%= current_user.city %> <br>
        <%= current_user.phone %> <br>
        <%= current_user.email %> <br>
        <%= current_user.url %> <br>
        Bank no: <%= current_user.bank_number %> <br>
        Bank name: <%= current_user.bank_name %> <br>
        VAT reg no: <%= current_user.fat_code %> <br>
        Chambers no: <%= current_user.chambers %> <br>
      </div>
    </div>
    <div class="row">
      <div class="addres-heading">
        <%= @invoice.client.company_name if @invoice.client.company_name %> <br>
        <%= @invoice.client.name %> <br>
        <%= @invoice.client.street %> <%= @invoice.client.number %> <br>
        <%= @invoice.client.zipcode %> <%= @invoice.client.city %> <br>
      </div>
    </div>
    <div class="row">
      <table class="table">
        <thead>
          <th>Description</th>
          <th>Amount</th>
          <th>Single Price<br>(excl. VAT)</th>
          <th>Total Price<br>(excl. VAT)</th>
        </thead>
        <tbody>
          <% @invoice.activities.each do |a| %>
            <tr>
              <td>
                <%= a.description %>
              </td>
              <td>
                <%= a.amount %>
              </td>
              <td>
                <%= number_to_currency(a.price_ex_fat, unit: "€ ", separator: ",") %>
              </td>
              <td>
                <%= number_to_currency(total_item_price_excl_vat(a.price_ex_fat, a.amount), unit: "€ ", separator: ",") %>
              </td>
            </tr>
          <% end %>
            <tr>
              <td colspan="2"></td>
              <td><b>Total (Excl. VAT):</b></td>
              <td><b><%= number_to_currency(total_price_excl_vat(@invoice), unit: "€ ", separator: ",")  %>
            </tr>
            <tr><td colspan="4"></td></tr>
            <tr>
              <td colspan="2"></td>
              <td><b>VAT:</b></td>
              <td><b><%= number_to_currency(vat(@invoice), unit: "€ ", separator: ",")  %>
            </tr>
            <tr>
              <td colspan="2"></td>
              <td><b>Total (Incl. VAT):</b></td>
              <td><b><%= number_to_currency(total_price_incl_vat(@invoice), unit: "€ ", separator: ",")  %>
            </tr>
        </tbody>
      </table>
    </div>
    <div class="row">
      <p class="payment-instructions center-block">
        <%= current_user.payment_instructions %></div>
      </p>
  </div>
</div>