config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    root 'pages#index', as: :root
  end

  root 'pages#public_index', as: :public_root

  resources :clients

  resources :invoices do
    resources :activities
  end

end

app/models/client.rb
# == Schema Information
#
# Table name: clients
#
#  id            :integer          not null, primary key
#  client_number :integer
#  name          :string
#  street        :string
#  number        :integer
#  zipcode       :string
#  city          :string
#  url           :string
#  email         :string
#  company_name  :string
#  phone         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Client < ActiveRecord::Base
  # Relations
  has_many :invoices

  def select_option
    if company_name == ''
      "#{name}"
    else
      "#{company_name} - #{name}"
    end
  end
end

app/controllers/clients_controller.rb
# == Schema Information
#
# Table name: clients
#
#  id            :integer          not null, primary key
#  client_number :integer
#  name          :string
#  street        :string
#  number        :integer
#  zipcode       :string
#  city          :string
#  url           :string
#  email         :string
#  company_name  :string
#  phone         :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class ClientsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_client, only: [:edit, :show, :update, :destroy]

  def index
    @clients = Client.all
  end

  def show
  end

  def new
    @client = Client.new
  end

  def create
    @client = Client.new(client_params)
    if @client.save
      redirect_to clients_path
      flash[:notice] = :saved
    else
      redirect_to new_client_path

      @client.errors.messages.each do |c|
        flash[:alert] = c[1].first
      end
    end
  end

  def edit
  end

  def update
    if @client.update(client_params)
      redirect_to clients_path
      flash[:notice] = :saved
    else
      @client.errors.messages.each do |c|
        flash[:alert] = c[1].first
      end
      render :edit
    end
  end

  def destroy
    redirect_to clients_path if @client.destroy
  end

  private

  def set_client
    @client = Client.find(params[:id])
  end

  def client_params
    params.require(:client).permit(:name, :street, :number, :zipcode, :city,
                                   :url, :email, :company_name, :phone,
                                   :client_number)
  end

end

app/views/clients/edit.html.erb
<h1 class="page-header">Edit a client</h1>
<%= form_for @client do |f| %>
  <div class="well">
    <div class="form-group">
      <%= f.label :company_name %><br />
      <%= f.text_field :company_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :client_number %><br />
      <%= f.text_field :client_number, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :street %> & <%= f.label :number %><br />
      <%= f.text_field :street %>
      <%= f.text_field :number %>
    </div>

    <div class="form-group">
      <%= f.label :zipcode %><br />
      <%= f.text_field :zipcode, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :city %><br />
      <%= f.text_field :city, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :url %><br />
      <%= f.text_field :url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email %><br />
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :phone %><br />
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
    <%= link_to "Back", clients_path, class: "btn btn-default"  %>
  </div>
<% end %>

app/views/clients/index.html.erb
<h1 class="page-header">Clients</h1>

<div class="panel panel-default">
  <div class="panel-heading">
  </div>
  <table class="table">
    <thead>
      <tr>
        <th>Number</th>
        <th>Company</th>
        <th>Name</th>
        <th>Email</th>
        <th>Website</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @clients.each do |c| %>
        <tr>
          <td>
            <%= "%.6d" % c.client_number %>
          </td>
          <td>
            <%= c.company_name %>
          </td>
          <td>
            <%= c.name %>
          </td>
          <td>
            <%= c.email %>
          </td>
          <td>
            <%= c.url %>
          </td>
          <td>
            <%= link_to (content_tag :span, (), class: 'fa fa-eye fa-fw'), client_path(c), class: 'btn btn-primary', title: 'Show'  %>
            <%= link_to (content_tag :span, (), class: 'fa fa-pencil fa-fw'), edit_client_path(c), class: 'btn btn-info', title: 'Edit'  %>
            <%= link_to (content_tag :span, (), class: 'fa fa-remove fa-fw'), client_path(c), class: 'btn btn-danger', title: 'Delete', method: :delete, data: { :confirm => "Are you sure?" } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class="panel-footer">
    <%= link_to (content_tag :span, (), class: 'fa fa-plus fa-fw') + " New Client", new_client_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/clients/new.html.erb
<h1 class="page-header">Create a new client</h1>
<%= form_for @client do |f| %>
  <div class="well">
    <div class="form-group">
      <%= f.label :company_name %><br />
      <%= f.text_field :company_name, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :client_number %><br />
      <%= f.text_field :client_number, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :name %><br />
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :street %> & <%= f.label :number %><br />
      <%= f.text_field :street %>
      <%= f.text_field :number %>
    </div>

    <div class="form-group">
      <%= f.label :zipcode %><br />
      <%= f.text_field :zipcode, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :city %><br />
      <%= f.text_field :city, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :url %><br />
      <%= f.text_field :url, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :email %><br />
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :phone %><br />
      <%= f.text_field :phone, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.submit 'Submit', class: "btn btn-primary" %>
    <%= link_to "Back", clients_path, class: "btn btn-default"  %>
  </div>
<% end %>

app/views/clients/show.html.erb
<h1 class="page-header">Client Info</h1>
<div class="panel panel-default">
  <div class="panel-heading">Client info</div>
  <div class="panel-body">
    <%= @client.company_name %> <br>
    <%= @client.name %> <br>
    <%= @client.street %> <%= @client.number %> <br>
    <%= @client.zipcode %> <%= @client.city %> <br>
    <%= @client.phone %> <br>
    <%= @client.email %> <br>
    <%= @client.url %> <br>
  </div>
</div>
<%= link_to "Back", clients_path, class: "btn btn-default"  %>