config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }

  authenticated :user do
    root 'pages#index', as: :root
  end

  root 'pages#public_index', as: :public_root

  resources :clients

  resources :invoices do
    resources :activities
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InvoiceProject</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/metisMenu/2.4.0/metisMenu.min.css">
  <script src="//cdnjs.cloudflare.com/ajax/libs/metisMenu/2.4.0/metisMenu.min.js"></script>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %>

  <div id="wrapper">

    <nav class="navbar navbar-inverse navbar-static-top" role="navigation" style="margin-bottom: 0">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to (content_tag :i, (), class: 'fa fa-credit-card-alt fa-fw') + ' Project Invoiced', root_path, class: 'navbar-brand' %>
      </div>

      <ul class="nav navbar-top-links navbar-right">
        <li class="dropdown">
          <a class="dropdown-toggle" data-toggle="dropdown" href="#">
              <i class="fa fa-user fa-fw"></i>  <i class="fa fa-caret-down"></i>
          </a>
          <ul class="dropdown-menu dropdown-user">
            <li><a href="#"><i class="fa fa-user fa-fw"></i> User Profile</a>
            </li>
            <li>
              <%= link_to (content_tag :i, (), class: 'fa fa-gear fa-fw') + ' Settings', edit_user_registration_path %>
            </li>
            <li class="divider"></li>
            <li>
              <%= link_to (content_tag :i, (), class: 'fa fa-sign-out fa-fw') + ' Logout', destroy_user_session_path, method: :delete  %>
            </li>
          </ul>
        </li>
      </ul>

      <div class="navbar sidebar" role="navigation">
        <div class="sidebar-nav navbar-collapse">
          <ul class="nav" id="side-menu">
            <li class="sidebar-search">
              <div class="input-group custom-search-form">
                <input type="text" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                  <button class="btn btn-default" type="button">
                    <i class="fa fa-search"></i>
                  </button>
                </span>
              </div>
            </li>
            <li class="active">
              <%= link_to (content_tag :i, (), class: 'fa fa-dashboard fa-fw') + ' Dashboard', root_path %>
            </li>
            <li>
              <%= link_to (content_tag :i, (), class: 'fa fa-users fa-fw') + ' Clients', clients_path %>
            </li>
            <li>
              <%= link_to (content_tag :i, (), class: 'fa fa-file-text fa-fw') + ' Invoices', invoices_path %>
            </li>
            <!-- <li>
              <a href="#"><i class="fa fa-files-o fa-fw"></i> Sample Pages<span class="fa arrow"></span></a>
              <ul class="nav nav-second-level">
                <li>
                  <a href="blank.html">Blank Page</a>
                </li>
                <li>
                  <a href="login.html">Login Page</a>
                </li>
              </ul>
            </li> -->
          </ul>
        </div>
      </div>
    </nav>

    <div id="page-wrapper">
      <div class="container-fluid">
        <div class="row">
          <div class="col-lg-12">
            <%= yield %>
          </div>
        </div>
      </div>
    </div>
  </div>

</body>
</html>